/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditExamSubjectsAndBatches.java
 *
 * Created on Mar 22, 2012, 11:21:41 AM
 */
package gui;

import core.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Absentees extends javax.swing.JFrame {

    static String currentAttendanceExamID;

    /** Creates new form EditExamSubjectsAndBatches
     * @throws java.sql.SQLException */
    public Absentees() throws SQLException {
        initComponents();
        // initial load
        loadDataToFields();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Absentees");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                windowGF(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jButton10.setText("Add Absentees");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addAbsentee_MP(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Absentee Details"));

        jButton12.setText("Remove");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeAbsentee_MP(evt);
            }
        });

        jLabel22.setText("Reg No.");

        jLabel23.setText("Name");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder("Absentees List"));

        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                absenteeList_MP(evt);
            }
        });
        jScrollPane7.setViewportView(jList4);

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(570, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAbsentee_MP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAbsentee_MP
        AddAbsentee.ExamID = currentAttendanceExamID;
        AddAbsentee.main(null);
}//GEN-LAST:event_addAbsentee_MP

    private void removeAbsentee_MP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAbsentee_MP
        if (!absenteeID.isEmpty()) {
            if (JOptionPane.showConfirmDialog(rootPane, "Delete This Absentee?", "Absentee Delete", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                if (DB.executeUpdate("delete from absentees where id = " + absenteeID)) {
                    JOptionPane.showMessageDialog(rootPane, "Absentee Deleted");
                    DB.flushStatementOnly();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Absentee Deletion Failed !!!");
                }
            }
            loadDataToFields();
        } 
        else {
            JOptionPane.showMessageDialog(rootPane, "Select a Absentee !!!");
        }
}//GEN-LAST:event_removeAbsentee_MP
    String absenteeID = "";
    private void absenteeList_MP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absenteeList_MP
        if (jList4.getSelectedValue() != null) {
            String studentregno = jList4.getSelectedValue().toString();

            ResultSet r = DB.executeQuery("select * from absentees where studentregno = '" + studentregno + "' and examid = " + currentAttendanceExamID);
            try {
                r.next();
                jTextField2.setText(studentregno);
                absenteeID = r.getString("id");
                r = DB.executeQuery("select name from students where regno='" + studentregno + "'");
                r.next();
                jTextField1.setText(r.getString("name"));
            } catch (Exception ex) {
                Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                DB.flushStatementOnly();
            }
        }
}//GEN-LAST:event_absenteeList_MP

    private void search_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_actionPerformed
        try {
            ResultSet r = null;

            if (!jTextField3.getText().isEmpty()) {
                r = DB.executeQuery("select * from absentees where studentregno like '" + jTextField3.getText() + "%' and examid=" + currentAttendanceExamID);
            } else {
                r = DB.executeQuery("select * from absentees where examid=" + currentAttendanceExamID);
            }
            Vector v = new Vector();
            while (r != null && r.next()) {
                v.add(r.getString("studentregno"));
            }
            jList4.setListData(v);
            DB.flushStatementOnly();
        } catch (SQLException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            DB.flushStatementOnly();
        }
    }//GEN-LAST:event_search_actionPerformed

    private void windowGF(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowGF
        loadDataToFields();
    }//GEN-LAST:event_windowGF

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Absentees().setVisible(true);
                } 
                catch (SQLException ex) {
                    Logger.getLogger(Absentees.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally {
                    DB.flushStatementOnly();
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void loadDataToFields() {
        try {
            ResultSet r = DB.executeQuery("select * from absentees where examid=" + currentAttendanceExamID);
            Vector v = new Vector();
            while (r != null && r.next()) {
                v.add(r.getString("studentregno"));
            }
            jList4.setListData(v);
            DB.flushStatementOnly();
        } 
        catch (SQLException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            DB.flushStatementOnly();
        }
    }
}
