/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddAbsentee.java
 *
 * Created on Mar 30, 2012, 1:28:55 PM
 */
package gui;

import core.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class AddAbsentee extends javax.swing.JFrame {

    public static String ExamID;

    /** Creates new form AddAbsentee */
    public AddAbsentee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Absentee");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Absentee Details"));

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMP(evt);
            }
        });

        jLabel1.setText("Reg No.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(277, 169));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMP
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            // check if valid student
            String studentId = jTextField1.getText();
            ResultSet r = DB.executeQuery("select * from students where regno = '" + studentId + "'");
            if (r != null && r.next()) {
                // check if student->batch-subject is there for the exam
                String batchId = r.getString("batchid");
                r = DB.executeQuery("select * from examsubjectandbatches where batchid = " + batchId);
                if (r != null && r.next()) {
                    r = DB.executeQuery("select * from absentees where studentregno = '" + studentId + "' and examid =" + ExamID);
                    if (r != null && r.next()) {
                        JOptionPane.showMessageDialog(rootPane, "Absentee already Added !!!");
                    } else {
                        if (DB.executeUpdate("insert into absentees values (null,'" + studentId + "'," + ExamID + ")")) {
                            JOptionPane.showMessageDialog(rootPane, "Absentee Added to Absentees List");
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Absentee Addition Failed !!!");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "This Student is not present \nin any of the Batches Selected \nfor this Examination");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid Student ID !!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddAbsentee.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            DB.flushStatementOnly();
        }
    }//GEN-LAST:event_addMP

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAbsentee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
