/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddBatch.java
 *
 * Created on Mar 14, 2012, 5:52:46 PM
 */
package gui;

import core.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class AddBatch extends javax.swing.JFrame {

    /** Creates new form AddBatch
     * @throws java.sql.SQLException */
    public AddBatch() throws SQLException {
        initComponents();

        // load schemes *****
        Vector v = new Vector();
        v.add("Select Scheme");
        ResultSet r = DB.executeQuery("select id from schemes");
        if (r != null) {
            while (r.next()) {
                v.add(r.getString("id"));
            }
        }
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(v));
        DB.flushStatementOnly();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField21 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jButton21 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Batch");

        jButton20.setText("Add");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addmp(evt);
            }
        });

        jButton21.setText("Cancel");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelmp(evt);
            }
        });

        jLabel18.setText("Name");

        jLabel20.setText("Scheme");

        jLabel19.setText("Batch No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, 0, 178, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(268, 193));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelmp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelmp
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelmp

    private void addmp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmp
        if (jTextField22.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Enter Batch Name !!!");
        } 
        else if (jTextField21.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Enter Batch No. !!!");
        }
        else if (jComboBox7.getSelectedItem().toString().contentEquals("Select Scheme")) {
            JOptionPane.showMessageDialog(rootPane, "Select a Scheme !!!");
        }
        else {
            try {
                ResultSet r = DB.executeQuery("select * from batches where name='" + jTextField22.getText() + "' and id=" + jTextField21.getText() + " and schemeid='" + jComboBox7.getSelectedItem().toString() + "'");
                if (r != null && r.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Batch Already Exists !!!");
                }
                else {
                    if (DB.executeUpdate("insert into batches values(" + jTextField21.getText() + ",'" + jTextField22.getText() + "','" + jComboBox7.getSelectedItem().toString() + "')")) {
                        JOptionPane.showMessageDialog(rootPane, "Batch Added Susseccfully");
                    }
                    else {
                        JOptionPane.showMessageDialog(rootPane, "Batch Addition Failed !!!");
                    }
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(AddBatch.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                DB.flushStatementOnly();
            }
        }

    }//GEN-LAST:event_addmp

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new AddBatch().setVisible(true);
                } 
                catch (SQLException ex) {
                    Logger.getLogger(AddBatch.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally{
                    DB.flushStatementOnly();
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    // End of variables declaration//GEN-END:variables
}
