/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExamSeatingArranger.java
 *
 */
package gui;

import core.DB;
import core.SeatingArranger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class ExamSeatingArranger_HallSelect extends javax.swing.JFrame {

    /** Creates new form ExamSeatingArranger */
    public ExamSeatingArranger_HallSelect() {
        try {
            initComponents();
            loadDataToField();
        } 
        catch (SQLException ex) {
            Logger.getLogger(ExamSeatingArranger_HallSelect.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            DB.flushStatementOnly();
        }
    }

    private void loadDataToField() throws SQLException {
        // halls list
        DB.flushStatementOnly();
        Vector v = new Vector();
        ResultSet r = DB.executeQuery("select name from halls");
        if (r != null) {
            while (r.next()) {
                v.add(r.getString("name"));
            }
        }
        jList3.setListData(v);
        DB.flushStatementOnly();
        //.................. load previous selected data....................
        v = new Vector();
        r = DB.executeQuery("select hallname from selectedexamhalls where examid=" + SeatingArranger.ExamID );
        if (r != null) {
            while (r.next()) {
                v.add(r.getString("hallname"));
            }
            jList4.setListData(v);
            DB.flushStatementOnly();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hall Select");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ExamSeatingArranger_HallSelect.this.windowClosing(evt);
            }
        });

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Halls"));

        jScrollPane4.setViewportView(jList4);

        jButton9.setText("Add");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMp(evt);
            }
        });

        jButton16.setText("Remove");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeMp(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Hall List"));

        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(375, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMp
        if (jList3.getSelectedValue() != null) {
            String selectedClass = jList3.getSelectedValue().toString();

            // checking whether the class has been already added...
            boolean isAddedAlready = false;
            for (int i = 0; i < jList4.getModel().getSize(); i++) {
                if (jList4.getModel().getElementAt(i).toString().contentEquals(selectedClass)) {
                    isAddedAlready = true;
                    break;
                }
            }

            // if already added the notify ...
            if (isAddedAlready) {
                JOptionPane.showMessageDialog(rootPane, "Hall '" + selectedClass + "' has already added");
            } 
            else {
                // add it to the added list ...

                // storing previous values to a vector ..
                Vector v = new Vector();
                for (int i = 0; i < jList4.getModel().getSize(); i++) {
                    v.add(jList4.getModel().getElementAt(i).toString());
                }
                // add the newely selected class to vector ...
                v.add(selectedClass);
                // load the vector to the list ...
                jList4.setListData(v);
            }
        } 
        else {
            JOptionPane.showMessageDialog(rootPane, "Select a Hall To Be Added");
        }
}//GEN-LAST:event_addMp

    private void removeMp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMp
        if (jList4.getSelectedValue() != null) {
            String selectedClass = jList4.getSelectedValue().toString();

            // storing previous values to a vector ..
            Vector v = new Vector();
            for (int i = 0; i < jList4.getModel().getSize(); i++) {
                if (!jList4.getModel().getElementAt(i).toString().contentEquals(selectedClass)) {
                    v.add(jList4.getModel().getElementAt(i).toString());
                }
            }
            // load the vector to the list ...
            jList4.setListData(v);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Select a Hall To Be Removed");
        }
}//GEN-LAST:event_removeMp

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        //DB.flushStatementOnly();
        // clear previous data......................
        //DB.executeUpdate("delete from selectedexamhalls where examid=" + SeatingArranger.ExamID );
        // ......................................... SAVE ALL DATA .........................
        DB.flushStatementOnly();
            for (int i = 0; i < jList4.getModel().getSize(); i++) {
                if (!DB.executeUpdate("insert into selectedexamhalls values(null,'" + jList4.getModel().getElementAt(i).toString() + "'," + SeatingArranger.ExamID + ")")) {
                    JOptionPane.showMessageDialog(rootPane, "Error !!! Cannot Insert Selected hall to DB !!!");
                }
                DB.flushStatementOnly();
            }
            DB.flushStatementOnly();
    }//GEN-LAST:event_windowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ExamSeatingArranger_HallSelect().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
